---
development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: <`rake generate:session_secret`>
  MSG_KEY: <`rake generate:msg_key`>
  GOOGLE_OAUTH_URL: https://accounts.google.com/o/oauth2/v2/auth
  GOOGLE_TOKEN_URL: https://oauth2.googleapis.com/token
  GOOGLE_SCOPE: 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'
  GOOGLE_CLIENT_ID: <provided by Google>
  GOOGLE_CLIENT_SECRET: <provided by Google>
  GOOGLE_REDIRECT_URI: http://localhost:9292/auth/sso_callback

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: <`rake generate:session_secret`>
  MSG_KEY: <`rake generate:msg_key`>
  GOOGLE_OAUTH_URL: https://accounts.google.com/o/oauth2/v2/auth
  GOOGLE_TOKEN_URL: https://oauth2.googleapis.com/token
  GOOGLE_SCOPE: 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'
  GOOGLE_CLIENT_ID: <provided by Google>
  GOOGLE_CLIENT_SECRET: <provided by Google>
  GOOGLE_REDIRECT_URI: http://localhost:9292/auth/sso_callback

production:
  API_URL: <provisioned API URL (ending with api/[version])>
  APP_URL: <provisioned app URL (root without ending slash)>
  SESSION_SECRET: <`rake generate:session_secret`>
  MSG_KEY: <`rake generate:msg_key`>
  REDISCLOUD_URL: <provision Redis instance>
  GOOGLE_OAUTH_URL: https://accounts.google.com/o/oauth2/v2/auth
  GOOGLE_TOKEN_URL: https://oauth2.googleapis.com/token
  GOOGLE_SCOPE: 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'
  GOOGLE_CLIENT_ID: <provided by Google>
  GOOGLE_CLIENT_SECRET: <provided by Google>
  GOOGLE_REDIRECT_URI: <APP_URL root>/auth/sso_callback