---
development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET:               # Please run `rake generate:session_secret` for this field

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET:               # Please run `rake generate:session_secret` for this field
